#pragma once
enum EKeyWordType {
    programSy,      // program
    typeSy,         // type
    varSy,          // var
    procedureSy,    // procedure
    orSy,           // or
    andSy,          // and
    notSy,          // not
    divSy,          // div
    modSy,          // mod
    beginSy,        // begin
    endSy,          // end
    ifSy,           // if
    thenSy,         // then
    elseSy,         // else
    whileSy,        // while
    doSy,           // do
    repeatSy,       // repeat
    untilSy,        // until
    forSy,          // for
    toSy,           // to
    downtoSy,       // downto
    starSy,         // *
    slashSy,        // /
    equalSy,        // =
    commaSy,        // ,
    semicolonSy,    // ;
    colonSy,        // :
    pointSy,        // .
    arrowSy,        // ^
    leftparSy,      // (
    rightparSy,     // )
    lbracketSy,     // [
    rbracketSy,     // ]
    laterSy,        // <
    greaterSy,      // >
    laterequalSy,   // <=
    greaterequalSy, // >=
    latergreaterSy, // <>
    plusSy,         // +
    minusSy,        // -
    assignSy,       // :=
    twopointsSy,    // ..
};